name: Publish image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build docker-image
        run: docker build -t ubevg/frontend .
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: push
        run: docker push ubevg/frontend:latest
      - name: webhook
        run: curl -X POST http://193.191.176.92:9000/api/webhooks/69557711-8c2a-4d6c-9c4e-0b4e7cdf6a4a